### ISSUE TITLE
Incorrect pattern for comparison content

### ISSUE THREAD

**Issue by boars** [qld-gov-au/pattern-library#5]
The pattern for the advantage vs disadvantage comparison columns has incorrect classes in it. 
- "advantages" should be "advantage"
- "disadvantages" should be "disadvantage"

Alternatively the CSS could be changed to match the pattern - dependant on how widely used the pattern is however. ie if already being used by pages, the pattern should be updated to reflect this instead of the CSS change.

https://github.com/qld-gov-au/pattern-library/blob/master/source/content-types/content-patterns/content-patterns.md

**Comment by bboyle** [comment]
or use both classnames: `.advantages, .advantage`
