### ISSUE TITLE
Page Models not available outside of GovDex :(

### ISSUE THREAD

**Issue by stevensimon** [qld-gov-au/pattern-library#6]
https://github.com/qld-gov-au/pattern-library/blob/master/source/page-models/page-models.md

Any chance of these being migrated over so the Page Models are accessible from the public?

Cheers,
Steve

**Comment by jennyyee** [comment]
Hi Steve

The page models are being updated, and the plan is to eventually make the new versions public, but this current version won’t be made public.

Cheers

[cid:image004.png@01D0868A.04DDFBD0]Jenny Yee
A/Content Management Officer
One-Stop Shop Strategy and Implementation Office
Department of Science, Information Technology and Innovation
­­­__________________________________________________________________
P 3719 7805
Level 10, 111 George St, BRISBANE  QLD  4000
GPO Box 5078, BRISBANE  QLD  4001
Customers first | Ideas into action | Unleash potential | Be courageous | Empower people
